/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_petuska_fake_kamera_jni_FakeCam */

#ifndef _Included_dev_petuska_fake_kamera_jni_FakeCam
#define _Included_dev_petuska_fake_kamera_jni_FakeCam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_petuska_fake_kamera_jni_FakeCam
 * Method:    open
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_dev_petuska_fake_kamera_jni_FakeCam_open
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     dev_petuska_fake_kamera_jni_FakeCam
 * Method:    writeFrame
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_petuska_fake_kamera_jni_FakeCam_writeFrame
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     dev_petuska_fake_kamera_jni_FakeCam
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dev_petuska_fake_kamera_jni_FakeCam_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
